name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 isort black pytest coverage
      - name: Run checks
        run: ./scripts/checks.sh
      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Render pattern previews
        run: |
          python scripts/pattern_visualize.py \
            --pattern-dir tests/fixtures/patterns \
            --output-dir build/pattern_previews \
            --archive build/pattern-previews.zip \
            --force
        continue-on-error: true
      - name: Upload pattern previews
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pattern-previews
          path: |
            build/pattern-previews.zip
            build/pattern_previews
          if-no-files-found: ignore
