name: docs
on:
  push:
    branches: [main]
  pull_request:
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install doc dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
      - name: Build HTML docs with Sphinx (warnings as errors)
        run: |
          sphinx-build -b html -W docs docs/_build
      - name: Upload built docs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: docs/_build/html
